# 02 — Manuscript Baseline Experiments

This notebook trains published baselines with independent random seeds and evaluates them on:

- the balanced severity–duration scenario grid;
- the sparse mixed-fault test;
- natural Gas Sensor batch shift;
- native SKAB anomaly sequences;
- a validation-only threshold sensitivity grid.

Duplicate experiment keys are skipped automatically.

In [1]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd().resolve()
if PROJECT_ROOT.name == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent
sys.path.insert(0, str(PROJECT_ROOT / "src"))

import numpy as np
import pandas as pd
from IPython.display import Image, Markdown, display

from drift_detection.config import load_config

config = load_config()
print(f"Project root: {PROJECT_ROOT}")
print(f"Experiment version: {config['project']['experiment_version']}")
print(f"Scenario profile: {config['experiment']['profile']}")

import importlib.util
from drift_detection.experiments_v2 import manuscript_result_root, run_baseline_manuscript_suite

Project root: /home/commu10/Documents/BT/cross_domain_drift_detection_manuscript_v2/cross_domain_drift_detection
Experiment version: manuscript_v2
Scenario profile: manuscript

## Controls

For final manuscript results, use all configured seeds. Install `requirements-sota.txt` before enabling published SOTA comparators.

In [2]:
SEEDS = list(config["project"]["seed_list"])
FORCE_RERUN = False
DEEPOD_AVAILABLE = importlib.util.find_spec("deepod") is not None
RUN_OPTIONAL_SOTA = DEEPOD_AVAILABLE

print("Independent seeds:", SEEDS)
print("DeepOD available:", DEEPOD_AVAILABLE)
print("Optional SOTA enabled:", RUN_OPTIONAL_SOTA)
if not DEEPOD_AVAILABLE:
    print("Install requirements-sota.txt and rerun this notebook before manuscript submission.")

Independent seeds: [42, 52, 62, 72, 82]
DeepOD available: False
Optional SOTA enabled: False
Install requirements-sota.txt and rerun this notebook before manuscript submission.

## Required benchmark files

In [3]:
required = [
    config["paths"]["benchmarks"] / "gas_controlled.npz",
    config["paths"]["benchmarks"] / "skab_controlled.npz",
    config["paths"]["benchmarks"] / "gas_sensor_scenario_manifest.csv",
    config["paths"]["benchmarks"] / "skab_scenario_manifest.csv",
]
missing = [str(path) for path in required if not path.exists()]
if missing:
    raise FileNotFoundError("Run Notebook 01 first:\n" + "\n".join(missing))

## Gas Sensor baselines

In [4]:
gas_baselines = run_baseline_manuscript_suite(
    config["paths"]["benchmarks"] / "gas_controlled.npz",
    dataset="gas_sensor",
    config=config,
    seeds=SEEDS,
    run_optional_sota=RUN_OPTIONAL_SOTA,
    force=FORCE_RERUN,
)
display(gas_baselines[[column for column in ["model", "seed", "status", "f1", "auprc", "event_recall", "false_positive_rate"] if column in gas_baselines.columns]])

2026-07-29 07:33:09,656 | INFO | RUN_STARTED | dataset=gas_sensor model=PCA_SPE seed=42
/home/commu10/.local/lib/python3.12/site-packages/torch/cuda/__init__.py:1061: UserWarning: Can't initialize NVML
  raw_cnt = _raw_device_count_nvml()
2026-07-29 07:33:51,543 | INFO | RUN_FINISHED | status=completed
/home/commu10/.local/lib/python3.12/site-packages/torch/cuda/__init__.py:1061: UserWarning: Can't initialize NVML
  raw_cnt = _raw_device_count_nvml()
2026-07-29 07:33:51,562 | INFO | RUN_STARTED | dataset=gas_sensor model=IsolationForest seed=42
2026-07-29 07:34:36,597 | INFO | RUN_FINISHED | status=completed
2026-07-29 07:34:36,608 | INFO | RUN_STARTED | dataset=gas_sensor model=DenseAE seed=42

Epoch 1/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 2/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 3/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 4/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 5/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 6/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 7/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 8/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 9/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 10/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 11/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 12/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 13/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 14/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 15/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 16/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 17/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 18/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 19/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 20/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 21/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 22/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 23/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 24/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 25/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 26/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 27/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 28/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 29/30:   0%|          | 0/4 [00:00<?, ?it/s]

2026-07-29 07:35:12,475 | INFO | RUN_FINISHED | status=completed
2026-07-29 07:35:12,485 | INFO | RUN_STARTED | dataset=gas_sensor model=LSTMAE seed=42

Epoch 1/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 2/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 3/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 4/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 5/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 6/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 7/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 8/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 9/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 10/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 11/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 12/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 13/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 14/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 15/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 16/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 17/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 18/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 19/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 20/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 21/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 22/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 23/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 24/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 25/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 26/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 27/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 28/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 29/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 30/30:   0%|          | 0/4 [00:00<?, ?it/s]

2026-07-29 07:35:49,601 | INFO | RUN_FINISHED | status=completed
2026-07-29 07:35:49,806 | INFO | RUN_STARTED | dataset=gas_sensor model=ConvAE seed=42

Epoch 1/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 2/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 3/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 4/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 5/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 6/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 7/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 8/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 9/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 10/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 11/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 12/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 13/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 14/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 15/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 16/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 17/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 18/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 19/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 20/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 21/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 22/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 23/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 24/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 25/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 26/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 27/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 28/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 29/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 30/30:   0%|          | 0/4 [00:00<?, ?it/s]

2026-07-29 07:36:26,696 | INFO | RUN_FINISHED | status=completed
2026-07-29 07:36:26,707 | INFO | RUN_STARTED | dataset=gas_sensor model=USAD seed=42

USAD epoch 1/30:   0%|          | 0/4 [00:00<?, ?it/s]

USAD epoch 2/30:   0%|          | 0/4 [00:00<?, ?it/s]

USAD epoch 3/30:   0%|          | 0/4 [00:00<?, ?it/s]

USAD epoch 4/30:   0%|          | 0/4 [00:00<?, ?it/s]

USAD epoch 5/30:   0%|          | 0/4 [00:00<?, ?it/s]

USAD epoch 6/30:   0%|          | 0/4 [00:00<?, ?it/s]

USAD epoch 7/30:   0%|          | 0/4 [00:00<?, ?it/s]

USAD epoch 8/30:   0%|          | 0/4 [00:00<?, ?it/s]

USAD epoch 9/30:   0%|          | 0/4 [00:00<?, ?it/s]

USAD epoch 10/30:   0%|          | 0/4 [00:00<?, ?it/s]

USAD epoch 11/30:   0%|          | 0/4 [00:00<?, ?it/s]

USAD epoch 12/30:   0%|          | 0/4 [00:00<?, ?it/s]

USAD epoch 13/30:   0%|          | 0/4 [00:00<?, ?it/s]

USAD epoch 14/30:   0%|          | 0/4 [00:00<?, ?it/s]

USAD epoch 15/30:   0%|          | 0/4 [00:00<?, ?it/s]

2026-07-29 07:37:03,045 | INFO | RUN_FINISHED | status=completed
2026-07-29 07:37:03,055 | INFO | RUN_STARTED | dataset=gas_sensor model=PCA_SPE seed=52
2026-07-29 07:37:44,508 | INFO | RUN_FINISHED | status=completed
2026-07-29 07:37:44,518 | INFO | RUN_STARTED | dataset=gas_sensor model=IsolationForest seed=52
2026-07-29 07:38:31,540 | INFO | RUN_FINISHED | status=completed
2026-07-29 07:38:31,551 | INFO | RUN_STARTED | dataset=gas_sensor model=DenseAE seed=52

Epoch 1/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 2/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 3/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 4/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 5/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 6/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 7/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 8/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 9/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 10/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 11/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 12/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 13/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 14/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 15/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 16/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 17/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 18/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 19/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 20/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 21/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 22/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 23/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 24/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 25/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 26/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 27/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 28/30:   0%|          | 0/4 [00:00<?, ?it/s]

2026-07-29 07:39:07,031 | INFO | RUN_FINISHED | status=completed
2026-07-29 07:39:07,040 | INFO | RUN_STARTED | dataset=gas_sensor model=LSTMAE seed=52

Epoch 1/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 2/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 3/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 4/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 5/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 6/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 7/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 8/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 9/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 10/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 11/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 12/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 13/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 14/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 15/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 16/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 17/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 18/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 19/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 20/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 21/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 22/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 23/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 24/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 25/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 26/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 27/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 28/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 29/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 30/30:   0%|          | 0/4 [00:00<?, ?it/s]

2026-07-29 07:39:43,840 | INFO | RUN_FINISHED | status=completed
2026-07-29 07:39:43,849 | INFO | RUN_STARTED | dataset=gas_sensor model=ConvAE seed=52

Epoch 1/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 2/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 3/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 4/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 5/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 6/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 7/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 8/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 9/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 10/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 11/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 12/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 13/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 14/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 15/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 16/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 17/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 18/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 19/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 20/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 21/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 22/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 23/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 24/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 25/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 26/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 27/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 28/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 29/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 30/30:   0%|          | 0/4 [00:00<?, ?it/s]

2026-07-29 07:40:20,242 | INFO | RUN_FINISHED | status=completed
2026-07-29 07:40:20,252 | INFO | RUN_STARTED | dataset=gas_sensor model=USAD seed=52

USAD epoch 1/30:   0%|          | 0/4 [00:00<?, ?it/s]

USAD epoch 2/30:   0%|          | 0/4 [00:00<?, ?it/s]

USAD epoch 3/30:   0%|          | 0/4 [00:00<?, ?it/s]

USAD epoch 4/30:   0%|          | 0/4 [00:00<?, ?it/s]

USAD epoch 5/30:   0%|          | 0/4 [00:00<?, ?it/s]

USAD epoch 6/30:   0%|          | 0/4 [00:00<?, ?it/s]

USAD epoch 7/30:   0%|          | 0/4 [00:00<?, ?it/s]

USAD epoch 8/30:   0%|          | 0/4 [00:00<?, ?it/s]

USAD epoch 9/30:   0%|          | 0/4 [00:00<?, ?it/s]

USAD epoch 10/30:   0%|          | 0/4 [00:00<?, ?it/s]

USAD epoch 11/30:   0%|          | 0/4 [00:00<?, ?it/s]

2026-07-29 07:40:56,480 | INFO | RUN_FINISHED | status=completed
2026-07-29 07:40:56,491 | INFO | RUN_STARTED | dataset=gas_sensor model=PCA_SPE seed=62
2026-07-29 07:41:39,072 | INFO | RUN_FINISHED | status=completed
2026-07-29 07:41:39,083 | INFO | RUN_STARTED | dataset=gas_sensor model=IsolationForest seed=62
2026-07-29 07:42:25,124 | INFO | RUN_FINISHED | status=completed
2026-07-29 07:42:25,134 | INFO | RUN_STARTED | dataset=gas_sensor model=DenseAE seed=62

Epoch 1/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 2/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 3/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 4/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 5/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 6/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 7/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 8/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 9/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 10/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 11/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 12/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 13/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 14/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 15/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 16/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 17/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 18/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 19/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 20/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 21/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 22/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 23/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 24/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 25/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 26/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 27/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 28/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 29/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 30/30:   0%|          | 0/4 [00:00<?, ?it/s]

2026-07-29 07:43:00,575 | INFO | RUN_FINISHED | status=completed
2026-07-29 07:43:00,585 | INFO | RUN_STARTED | dataset=gas_sensor model=LSTMAE seed=62

Epoch 1/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 2/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 3/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 4/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 5/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 6/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 7/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 8/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 9/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 10/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 11/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 12/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 13/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 14/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 15/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 16/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 17/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 18/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 19/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 20/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 21/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 22/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 23/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 24/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 25/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 26/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 27/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 28/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 29/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 30/30:   0%|          | 0/4 [00:00<?, ?it/s]

2026-07-29 07:43:37,682 | INFO | RUN_FINISHED | status=completed
2026-07-29 07:43:37,691 | INFO | RUN_STARTED | dataset=gas_sensor model=ConvAE seed=62

Epoch 1/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 2/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 3/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 4/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 5/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 6/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 7/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 8/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 9/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 10/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 11/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 12/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 13/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 14/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 15/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 16/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 17/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 18/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 19/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 20/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 21/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 22/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 23/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 24/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 25/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 26/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 27/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 28/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 29/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 30/30:   0%|          | 0/4 [00:00<?, ?it/s]

2026-07-29 07:44:14,397 | INFO | RUN_FINISHED | status=completed
2026-07-29 07:44:14,406 | INFO | RUN_STARTED | dataset=gas_sensor model=USAD seed=62

USAD epoch 1/30:   0%|          | 0/4 [00:00<?, ?it/s]

USAD epoch 2/30:   0%|          | 0/4 [00:00<?, ?it/s]

USAD epoch 3/30:   0%|          | 0/4 [00:00<?, ?it/s]

USAD epoch 4/30:   0%|          | 0/4 [00:00<?, ?it/s]

USAD epoch 5/30:   0%|          | 0/4 [00:00<?, ?it/s]

USAD epoch 6/30:   0%|          | 0/4 [00:00<?, ?it/s]

USAD epoch 7/30:   0%|          | 0/4 [00:00<?, ?it/s]

USAD epoch 8/30:   0%|          | 0/4 [00:00<?, ?it/s]

USAD epoch 9/30:   0%|          | 0/4 [00:00<?, ?it/s]

USAD epoch 10/30:   0%|          | 0/4 [00:00<?, ?it/s]

USAD epoch 11/30:   0%|          | 0/4 [00:00<?, ?it/s]

2026-07-29 07:44:50,650 | INFO | RUN_FINISHED | status=completed
2026-07-29 07:44:50,661 | INFO | RUN_STARTED | dataset=gas_sensor model=PCA_SPE seed=72
2026-07-29 07:45:33,149 | INFO | RUN_FINISHED | status=completed
2026-07-29 07:45:33,159 | INFO | RUN_STARTED | dataset=gas_sensor model=IsolationForest seed=72
2026-07-29 07:46:19,289 | INFO | RUN_FINISHED | status=completed
2026-07-29 07:46:19,299 | INFO | RUN_STARTED | dataset=gas_sensor model=DenseAE seed=72

Epoch 1/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 2/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 3/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 4/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 5/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 6/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 7/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 8/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 9/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 10/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 11/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 12/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 13/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 14/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 15/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 16/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 17/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 18/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 19/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 20/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 21/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 22/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 23/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 24/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 25/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 26/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 27/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 28/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 29/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 30/30:   0%|          | 0/4 [00:00<?, ?it/s]

2026-07-29 07:46:54,860 | INFO | RUN_FINISHED | status=completed
2026-07-29 07:46:54,870 | INFO | RUN_STARTED | dataset=gas_sensor model=LSTMAE seed=72

Epoch 1/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 2/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 3/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 4/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 5/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 6/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 7/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 8/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 9/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 10/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 11/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 12/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 13/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 14/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 15/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 16/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 17/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 18/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 19/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 20/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 21/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 22/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 23/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 24/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 25/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 26/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 27/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 28/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 29/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 30/30:   0%|          | 0/4 [00:00<?, ?it/s]

2026-07-29 07:47:33,097 | INFO | RUN_FINISHED | status=completed
2026-07-29 07:47:33,111 | INFO | RUN_STARTED | dataset=gas_sensor model=ConvAE seed=72

Epoch 1/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 2/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 3/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 4/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 5/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 6/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 7/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 8/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 9/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 10/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 11/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 12/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 13/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 14/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 15/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 16/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 17/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 18/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 19/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 20/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 21/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 22/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 23/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 24/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 25/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 26/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 27/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 28/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 29/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 30/30:   0%|          | 0/4 [00:00<?, ?it/s]

2026-07-29 07:48:09,839 | INFO | RUN_FINISHED | status=completed
2026-07-29 07:48:09,850 | INFO | RUN_STARTED | dataset=gas_sensor model=USAD seed=72

USAD epoch 1/30:   0%|          | 0/4 [00:00<?, ?it/s]

USAD epoch 2/30:   0%|          | 0/4 [00:00<?, ?it/s]

USAD epoch 3/30:   0%|          | 0/4 [00:00<?, ?it/s]

USAD epoch 4/30:   0%|          | 0/4 [00:00<?, ?it/s]

USAD epoch 5/30:   0%|          | 0/4 [00:00<?, ?it/s]

USAD epoch 6/30:   0%|          | 0/4 [00:00<?, ?it/s]

USAD epoch 7/30:   0%|          | 0/4 [00:00<?, ?it/s]

USAD epoch 8/30:   0%|          | 0/4 [00:00<?, ?it/s]

USAD epoch 9/30:   0%|          | 0/4 [00:00<?, ?it/s]

2026-07-29 07:48:45,827 | INFO | RUN_FINISHED | status=completed
2026-07-29 07:48:45,839 | INFO | RUN_STARTED | dataset=gas_sensor model=PCA_SPE seed=82
2026-07-29 07:49:28,814 | INFO | RUN_FINISHED | status=completed
2026-07-29 07:49:28,825 | INFO | RUN_STARTED | dataset=gas_sensor model=IsolationForest seed=82
2026-07-29 07:50:15,552 | INFO | RUN_FINISHED | status=completed
2026-07-29 07:50:15,563 | INFO | RUN_STARTED | dataset=gas_sensor model=DenseAE seed=82

Epoch 1/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 2/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 3/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 4/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 5/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 6/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 7/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 8/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 9/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 10/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 11/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 12/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 13/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 14/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 15/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 16/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 17/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 18/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 19/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 20/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 21/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 22/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 23/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 24/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 25/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 26/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 27/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 28/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 29/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 30/30:   0%|          | 0/4 [00:00<?, ?it/s]

2026-07-29 07:50:52,292 | INFO | RUN_FINISHED | status=completed
2026-07-29 07:50:52,302 | INFO | RUN_STARTED | dataset=gas_sensor model=LSTMAE seed=82

Epoch 1/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 2/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 3/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 4/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 5/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 6/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 7/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 8/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 9/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 10/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 11/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 12/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 13/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 14/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 15/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 16/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 17/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 18/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 19/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 20/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 21/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 22/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 23/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 24/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 25/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 26/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 27/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 28/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 29/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 30/30:   0%|          | 0/4 [00:00<?, ?it/s]

2026-07-29 07:51:30,284 | INFO | RUN_FINISHED | status=completed
2026-07-29 07:51:30,294 | INFO | RUN_STARTED | dataset=gas_sensor model=ConvAE seed=82

Epoch 1/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 2/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 3/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 4/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 5/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 6/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 7/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 8/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 9/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 10/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 11/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 12/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 13/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 14/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 15/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 16/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 17/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 18/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 19/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 20/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 21/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 22/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 23/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 24/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 25/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 26/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 27/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 28/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 29/30:   0%|          | 0/4 [00:00<?, ?it/s]

Epoch 30/30:   0%|          | 0/4 [00:00<?, ?it/s]

2026-07-29 07:52:07,160 | INFO | RUN_FINISHED | status=completed
2026-07-29 07:52:07,171 | INFO | RUN_STARTED | dataset=gas_sensor model=USAD seed=82

USAD epoch 1/30:   0%|          | 0/4 [00:00<?, ?it/s]

USAD epoch 2/30:   0%|          | 0/4 [00:00<?, ?it/s]

USAD epoch 3/30:   0%|          | 0/4 [00:00<?, ?it/s]

USAD epoch 4/30:   0%|          | 0/4 [00:00<?, ?it/s]

USAD epoch 5/30:   0%|          | 0/4 [00:00<?, ?it/s]

USAD epoch 6/30:   0%|          | 0/4 [00:00<?, ?it/s]

USAD epoch 7/30:   0%|          | 0/4 [00:00<?, ?it/s]

USAD epoch 8/30:   0%|          | 0/4 [00:00<?, ?it/s]

USAD epoch 9/30:   0%|          | 0/4 [00:00<?, ?it/s]

USAD epoch 10/30:   0%|          | 0/4 [00:00<?, ?it/s]

USAD epoch 11/30:   0%|          | 0/4 [00:00<?, ?it/s]

USAD epoch 12/30:   0%|          | 0/4 [00:00<?, ?it/s]

USAD epoch 13/30:   0%|          | 0/4 [00:00<?, ?it/s]

USAD epoch 14/30:   0%|          | 0/4 [00:00<?, ?it/s]

USAD epoch 15/30:   0%|          | 0/4 [00:00<?, ?it/s]

2026-07-29 07:52:43,691 | INFO | RUN_FINISHED | status=completed

,model,seed,status,f1,auprc,event_recall,false_positive_rate
0,PCA_SPE,42,completed,0.123927,0.160352,0.465278,0.165327
1,IsolationForest,42,completed,0.032045,0.180704,0.090278,0.036831
2,DenseAE,42,completed,0.066336,0.151519,0.333333,0.134504
3,LSTMAE,42,completed,0.079689,0.158146,0.354167,0.133960
4,ConvAE,42,completed,0.146398,0.164601,0.572917,0.181174
5,USAD,42,completed,0.056535,0.151475,0.298611,0.120688
6,PCA_SPE,52,completed,0.123927,0.160352,0.465278,0.165327
7,IsolationForest,52,completed,0.028692,0.179693,0.079861,0.029465
8,DenseAE,52,completed,0.067347,0.152343,0.333333,0.130913
9,LSTMAE,52,completed,0.084924,0.158849,0.368056,0.137512
10,ConvAE,52,completed,0.136947,0.163985,0.503472,0.172287
11,USAD,52,completed,0.055778,0.151345,0.291667,0.120688
12,PCA_SPE,62,completed,0.123927,0.160352,0.465278,0.165327
13,IsolationForest,62,completed,0.026141,0.179885,0.104167,0.029465
14,DenseAE,62,completed,0.068283,0.152303,0.315972,0.123706
15,LSTMAE,62,completed,0.072383,0.157433,0.326389,0.123706
16,ConvAE,62,completed,0.121990,0.162666,0.434028,0.133960
17,USAD,62,completed,0.055511,0.151296,0.291667,0.120688
18,PCA_SPE,72,completed,0.123927,0.160352,0.465278,0.165327
19,IsolationForest,72,completed,0.038422,0.180819,0.121528,0.036817
20,DenseAE,72,completed,0.076395,0.153284,0.343750,0.138095
21,LSTMAE,72,completed,0.075510,0.157701,0.336806,0.133960
22,ConvAE,72,completed,0.147487,0.163102,0.572917,0.177700
23,USAD,72,completed,0.055122,0.151299,0.291667,0.120688
24,PCA_SPE,82,completed,0.123927,0.160352,0.465278,0.165327
25,IsolationForest,82,completed,0.019392,0.177488,0.072917,0.025782
26,DenseAE,82,completed,0.084595,0.149972,0.368056,0.141142
27,LSTMAE,82,completed,0.070192,0.158770,0.326389,0.123706
28,ConvAE,82,completed,0.137431,0.164691,0.500000,0.168813
29,USAD,82,completed,0.056483,0.151345,0.298611,0.120688

## SKAB baselines

In [5]:
skab_baselines = run_baseline_manuscript_suite(
    config["paths"]["benchmarks"] / "skab_controlled.npz",
    dataset="skab",
    config=config,
    seeds=SEEDS,
    run_optional_sota=RUN_OPTIONAL_SOTA,
    force=FORCE_RERUN,
)
display(skab_baselines[[column for column in ["model", "seed", "status", "f1", "auprc", "event_recall", "false_positive_rate", "native_f1"] if column in skab_baselines.columns]])

2026-07-29 07:52:43,780 | INFO | RUN_STARTED | dataset=skab model=PCA_SPE seed=42
2026-07-29 07:53:20,236 | INFO | RUN_FINISHED | status=completed
2026-07-29 07:53:20,247 | INFO | RUN_STARTED | dataset=skab model=IsolationForest seed=42
2026-07-29 07:54:10,859 | INFO | RUN_FINISHED | status=completed
2026-07-29 07:54:10,870 | INFO | RUN_STARTED | dataset=skab model=DenseAE seed=42

Epoch 1/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 2/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 3/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 4/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 5/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 6/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 7/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 8/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 9/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 10/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 11/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 12/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 13/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 14/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 15/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 16/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 17/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 18/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 19/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 20/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 21/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 22/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 23/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 24/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 25/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 26/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 27/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 28/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 29/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 30/30:   0%|          | 0/11 [00:00<?, ?it/s]

2026-07-29 07:54:50,328 | INFO | RUN_FINISHED | status=completed
2026-07-29 07:54:50,339 | INFO | RUN_STARTED | dataset=skab model=LSTMAE seed=42

Epoch 1/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 2/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 3/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 4/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 5/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 6/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 7/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 8/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 9/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 10/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 11/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 12/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 13/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 14/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 15/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 16/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 17/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 18/30:   0%|          | 0/11 [00:00<?, ?it/s]

2026-07-29 07:55:30,909 | INFO | RUN_FINISHED | status=completed
2026-07-29 07:55:30,920 | INFO | RUN_STARTED | dataset=skab model=ConvAE seed=42

Epoch 1/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 2/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 3/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 4/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 5/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 6/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 7/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 8/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 9/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 10/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 11/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 12/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 13/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 14/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 15/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 16/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 17/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 18/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 19/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 20/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 21/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 22/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 23/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 24/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 25/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 26/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 27/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 28/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 29/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 30/30:   0%|          | 0/11 [00:00<?, ?it/s]

2026-07-29 07:56:10,934 | INFO | RUN_FINISHED | status=completed
2026-07-29 07:56:10,946 | INFO | RUN_STARTED | dataset=skab model=USAD seed=42

USAD epoch 1/30:   0%|          | 0/11 [00:00<?, ?it/s]

USAD epoch 2/30:   0%|          | 0/11 [00:00<?, ?it/s]

USAD epoch 3/30:   0%|          | 0/11 [00:00<?, ?it/s]

USAD epoch 4/30:   0%|          | 0/11 [00:00<?, ?it/s]

USAD epoch 5/30:   0%|          | 0/11 [00:00<?, ?it/s]

USAD epoch 6/30:   0%|          | 0/11 [00:00<?, ?it/s]

USAD epoch 7/30:   0%|          | 0/11 [00:00<?, ?it/s]

USAD epoch 8/30:   0%|          | 0/11 [00:00<?, ?it/s]

USAD epoch 9/30:   0%|          | 0/11 [00:00<?, ?it/s]

USAD epoch 10/30:   0%|          | 0/11 [00:00<?, ?it/s]

USAD epoch 11/30:   0%|          | 0/11 [00:00<?, ?it/s]

2026-07-29 07:56:50,719 | INFO | RUN_FINISHED | status=completed
2026-07-29 07:56:50,730 | INFO | RUN_STARTED | dataset=skab model=PCA_SPE seed=52
2026-07-29 07:57:25,548 | INFO | RUN_FINISHED | status=completed
2026-07-29 07:57:25,558 | INFO | RUN_STARTED | dataset=skab model=IsolationForest seed=52
2026-07-29 07:58:14,699 | INFO | RUN_FINISHED | status=completed
2026-07-29 07:58:14,710 | INFO | RUN_STARTED | dataset=skab model=DenseAE seed=52

Epoch 1/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 2/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 3/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 4/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 5/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 6/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 7/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 8/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 9/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 10/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 11/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 12/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 13/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 14/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 15/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 16/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 17/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 18/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 19/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 20/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 21/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 22/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 23/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 24/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 25/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 26/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 27/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 28/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 29/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 30/30:   0%|          | 0/11 [00:00<?, ?it/s]

2026-07-29 07:58:53,252 | INFO | RUN_FINISHED | status=completed
2026-07-29 07:58:53,262 | INFO | RUN_STARTED | dataset=skab model=LSTMAE seed=52

Epoch 1/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 2/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 3/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 4/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 5/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 6/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 7/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 8/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 9/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 10/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 11/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 12/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 13/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 14/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 15/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 16/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 17/30:   0%|          | 0/11 [00:00<?, ?it/s]

2026-07-29 07:59:32,749 | INFO | RUN_FINISHED | status=completed
2026-07-29 07:59:32,760 | INFO | RUN_STARTED | dataset=skab model=ConvAE seed=52

Epoch 1/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 2/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 3/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 4/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 5/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 6/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 7/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 8/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 9/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 10/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 11/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 12/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 13/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 14/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 15/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 16/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 17/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 18/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 19/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 20/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 21/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 22/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 23/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 24/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 25/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 26/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 27/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 28/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 29/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 30/30:   0%|          | 0/11 [00:00<?, ?it/s]

2026-07-29 08:00:11,522 | INFO | RUN_FINISHED | status=completed
2026-07-29 08:00:11,532 | INFO | RUN_STARTED | dataset=skab model=USAD seed=52

USAD epoch 1/30:   0%|          | 0/11 [00:00<?, ?it/s]

USAD epoch 2/30:   0%|          | 0/11 [00:00<?, ?it/s]

USAD epoch 3/30:   0%|          | 0/11 [00:00<?, ?it/s]

USAD epoch 4/30:   0%|          | 0/11 [00:00<?, ?it/s]

USAD epoch 5/30:   0%|          | 0/11 [00:00<?, ?it/s]

USAD epoch 6/30:   0%|          | 0/11 [00:00<?, ?it/s]

USAD epoch 7/30:   0%|          | 0/11 [00:00<?, ?it/s]

USAD epoch 8/30:   0%|          | 0/11 [00:00<?, ?it/s]

USAD epoch 9/30:   0%|          | 0/11 [00:00<?, ?it/s]

USAD epoch 10/30:   0%|          | 0/11 [00:00<?, ?it/s]

2026-07-29 08:00:50,309 | INFO | RUN_FINISHED | status=completed
2026-07-29 08:00:50,319 | INFO | RUN_STARTED | dataset=skab model=PCA_SPE seed=62
2026-07-29 08:01:24,649 | INFO | RUN_FINISHED | status=completed
2026-07-29 08:01:24,659 | INFO | RUN_STARTED | dataset=skab model=IsolationForest seed=62
2026-07-29 08:02:13,962 | INFO | RUN_FINISHED | status=completed
2026-07-29 08:02:13,974 | INFO | RUN_STARTED | dataset=skab model=DenseAE seed=62

Epoch 1/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 2/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 3/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 4/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 5/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 6/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 7/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 8/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 9/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 10/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 11/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 12/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 13/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 14/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 15/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 16/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 17/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 18/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 19/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 20/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 21/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 22/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 23/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 24/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 25/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 26/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 27/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 28/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 29/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 30/30:   0%|          | 0/11 [00:00<?, ?it/s]

2026-07-29 08:02:52,344 | INFO | RUN_FINISHED | status=completed
2026-07-29 08:02:52,355 | INFO | RUN_STARTED | dataset=skab model=LSTMAE seed=62

Epoch 1/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 2/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 3/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 4/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 5/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 6/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 7/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 8/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 9/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 10/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 11/30:   0%|          | 0/11 [00:00<?, ?it/s]

2026-07-29 08:03:30,221 | INFO | RUN_FINISHED | status=completed
2026-07-29 08:03:30,232 | INFO | RUN_STARTED | dataset=skab model=ConvAE seed=62

Epoch 1/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 2/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 3/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 4/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 5/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 6/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 7/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 8/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 9/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 10/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 11/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 12/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 13/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 14/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 15/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 16/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 17/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 18/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 19/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 20/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 21/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 22/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 23/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 24/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 25/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 26/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 27/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 28/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 29/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 30/30:   0%|          | 0/11 [00:00<?, ?it/s]

2026-07-29 08:04:09,439 | INFO | RUN_FINISHED | status=completed
2026-07-29 08:04:09,450 | INFO | RUN_STARTED | dataset=skab model=USAD seed=62

USAD epoch 1/30:   0%|          | 0/11 [00:00<?, ?it/s]

USAD epoch 2/30:   0%|          | 0/11 [00:00<?, ?it/s]

USAD epoch 3/30:   0%|          | 0/11 [00:00<?, ?it/s]

USAD epoch 4/30:   0%|          | 0/11 [00:00<?, ?it/s]

USAD epoch 5/30:   0%|          | 0/11 [00:00<?, ?it/s]

USAD epoch 6/30:   0%|          | 0/11 [00:00<?, ?it/s]

USAD epoch 7/30:   0%|          | 0/11 [00:00<?, ?it/s]

USAD epoch 8/30:   0%|          | 0/11 [00:00<?, ?it/s]

USAD epoch 9/30:   0%|          | 0/11 [00:00<?, ?it/s]

USAD epoch 10/30:   0%|          | 0/11 [00:00<?, ?it/s]

USAD epoch 11/30:   0%|          | 0/11 [00:00<?, ?it/s]

2026-07-29 08:04:49,139 | INFO | RUN_FINISHED | status=completed
2026-07-29 08:04:49,149 | INFO | RUN_STARTED | dataset=skab model=PCA_SPE seed=72
2026-07-29 08:05:25,178 | INFO | RUN_FINISHED | status=completed
2026-07-29 08:05:25,189 | INFO | RUN_STARTED | dataset=skab model=IsolationForest seed=72
2026-07-29 08:06:17,195 | INFO | RUN_FINISHED | status=completed
2026-07-29 08:06:17,209 | INFO | RUN_STARTED | dataset=skab model=DenseAE seed=72

Epoch 1/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 2/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 3/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 4/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 5/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 6/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 7/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 8/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 9/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 10/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 11/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 12/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 13/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 14/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 15/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 16/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 17/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 18/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 19/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 20/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 21/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 22/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 23/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 24/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 25/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 26/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 27/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 28/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 29/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 30/30:   0%|          | 0/11 [00:00<?, ?it/s]

2026-07-29 08:06:57,235 | INFO | RUN_FINISHED | status=completed
2026-07-29 08:06:57,245 | INFO | RUN_STARTED | dataset=skab model=LSTMAE seed=72

Epoch 1/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 2/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 3/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 4/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 5/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 6/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 7/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 8/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 9/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 10/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 11/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 12/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 13/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 14/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 15/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 16/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 17/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 18/30:   0%|          | 0/11 [00:00<?, ?it/s]

2026-07-29 08:07:37,851 | INFO | RUN_FINISHED | status=completed
2026-07-29 08:07:37,862 | INFO | RUN_STARTED | dataset=skab model=ConvAE seed=72

Epoch 1/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 2/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 3/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 4/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 5/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 6/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 7/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 8/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 9/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 10/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 11/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 12/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 13/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 14/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 15/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 16/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 17/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 18/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 19/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 20/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 21/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 22/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 23/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 24/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 25/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 26/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 27/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 28/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 29/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 30/30:   0%|          | 0/11 [00:00<?, ?it/s]

2026-07-29 08:08:17,622 | INFO | RUN_FINISHED | status=completed
2026-07-29 08:08:17,633 | INFO | RUN_STARTED | dataset=skab model=USAD seed=72

USAD epoch 1/30:   0%|          | 0/11 [00:00<?, ?it/s]

USAD epoch 2/30:   0%|          | 0/11 [00:00<?, ?it/s]

USAD epoch 3/30:   0%|          | 0/11 [00:00<?, ?it/s]

USAD epoch 4/30:   0%|          | 0/11 [00:00<?, ?it/s]

USAD epoch 5/30:   0%|          | 0/11 [00:00<?, ?it/s]

USAD epoch 6/30:   0%|          | 0/11 [00:00<?, ?it/s]

USAD epoch 7/30:   0%|          | 0/11 [00:00<?, ?it/s]

USAD epoch 8/30:   0%|          | 0/11 [00:00<?, ?it/s]

USAD epoch 9/30:   0%|          | 0/11 [00:00<?, ?it/s]

USAD epoch 10/30:   0%|          | 0/11 [00:00<?, ?it/s]

2026-07-29 08:08:57,979 | INFO | RUN_FINISHED | status=completed
2026-07-29 08:08:57,990 | INFO | RUN_STARTED | dataset=skab model=PCA_SPE seed=82
2026-07-29 08:09:34,013 | INFO | RUN_FINISHED | status=completed
2026-07-29 08:09:34,024 | INFO | RUN_STARTED | dataset=skab model=IsolationForest seed=82
2026-07-29 08:10:25,872 | INFO | RUN_FINISHED | status=completed
2026-07-29 08:10:25,884 | INFO | RUN_STARTED | dataset=skab model=DenseAE seed=82

Epoch 1/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 2/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 3/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 4/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 5/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 6/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 7/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 8/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 9/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 10/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 11/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 12/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 13/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 14/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 15/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 16/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 17/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 18/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 19/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 20/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 21/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 22/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 23/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 24/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 25/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 26/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 27/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 28/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 29/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 30/30:   0%|          | 0/11 [00:00<?, ?it/s]

2026-07-29 08:11:06,217 | INFO | RUN_FINISHED | status=completed
2026-07-29 08:11:06,230 | INFO | RUN_STARTED | dataset=skab model=LSTMAE seed=82

Epoch 1/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 2/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 3/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 4/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 5/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 6/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 7/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 8/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 9/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 10/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 11/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 12/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 13/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 14/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 15/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 16/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 17/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 18/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 19/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 20/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 21/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 22/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 23/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 24/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 25/30:   0%|          | 0/11 [00:00<?, ?it/s]

2026-07-29 08:11:48,418 | INFO | RUN_FINISHED | status=completed
2026-07-29 08:11:48,429 | INFO | RUN_STARTED | dataset=skab model=ConvAE seed=82

Epoch 1/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 2/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 3/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 4/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 5/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 6/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 7/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 8/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 9/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 10/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 11/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 12/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 13/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 14/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 15/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 16/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 17/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 18/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 19/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 20/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 21/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 22/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 23/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 24/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 25/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 26/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 27/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 28/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 29/30:   0%|          | 0/11 [00:00<?, ?it/s]

Epoch 30/30:   0%|          | 0/11 [00:00<?, ?it/s]

2026-07-29 08:12:29,035 | INFO | RUN_FINISHED | status=completed
2026-07-29 08:12:29,047 | INFO | RUN_STARTED | dataset=skab model=USAD seed=82

USAD epoch 1/30:   0%|          | 0/11 [00:00<?, ?it/s]

USAD epoch 2/30:   0%|          | 0/11 [00:00<?, ?it/s]

USAD epoch 3/30:   0%|          | 0/11 [00:00<?, ?it/s]

USAD epoch 4/30:   0%|          | 0/11 [00:00<?, ?it/s]

USAD epoch 5/30:   0%|          | 0/11 [00:00<?, ?it/s]

USAD epoch 6/30:   0%|          | 0/11 [00:00<?, ?it/s]

USAD epoch 7/30:   0%|          | 0/11 [00:00<?, ?it/s]

USAD epoch 8/30:   0%|          | 0/11 [00:00<?, ?it/s]

USAD epoch 9/30:   0%|          | 0/11 [00:00<?, ?it/s]

USAD epoch 10/30:   0%|          | 0/11 [00:00<?, ?it/s]

USAD epoch 11/30:   0%|          | 0/11 [00:00<?, ?it/s]

2026-07-29 08:13:09,020 | INFO | RUN_FINISHED | status=completed

,model,seed,status,f1,auprc,event_recall,false_positive_rate,native_f1
0,PCA_SPE,42,completed,0.220336,0.412898,0.864583,0.297524,0.578675
1,IsolationForest,42,completed,0.256997,0.317014,0.659722,0.069169,0.565488
2,DenseAE,42,completed,0.229607,0.428895,0.781250,0.237726,0.571577
3,LSTMAE,42,completed,0.221371,0.428869,0.781250,0.279677,0.562621
4,ConvAE,42,completed,0.209805,0.431070,0.843750,0.325760,0.558918
5,USAD,42,completed,0.202770,0.439204,0.920139,0.395180,0.556378
6,PCA_SPE,52,completed,0.218206,0.413365,0.871528,0.299878,0.578759
7,IsolationForest,52,completed,0.215875,0.296604,0.493056,0.046991,0.569115
8,DenseAE,52,completed,0.227942,0.423118,0.815972,0.261956,0.572770
9,LSTMAE,52,completed,0.221381,0.430707,0.770833,0.277319,0.563956
10,ConvAE,52,completed,0.223450,0.445716,0.777778,0.258038,0.557852
11,USAD,52,completed,0.201927,0.439021,0.902778,0.382571,0.556429
12,PCA_SPE,62,completed,0.218905,0.413558,0.857639,0.293427,0.579672
13,IsolationForest,62,completed,0.233127,0.318765,0.565972,0.064776,0.568372
14,DenseAE,62,completed,0.234004,0.437036,0.802083,0.244640,0.571505
15,LSTMAE,62,completed,0.209670,0.437953,0.888889,0.386288,0.557207
16,ConvAE,62,completed,0.206916,0.420704,0.892361,0.351167,0.557761
17,USAD,62,completed,0.212897,0.439253,0.881944,0.335778,0.556429
18,PCA_SPE,72,completed,0.217233,0.413477,0.871528,0.301773,0.579573
19,IsolationForest,72,completed,0.256767,0.325975,0.642361,0.082300,0.563367
20,DenseAE,72,completed,0.231509,0.434685,0.815972,0.257459,0.569462
21,LSTMAE,72,completed,0.220498,0.430318,0.770833,0.279834,0.563536
22,ConvAE,72,completed,0.182731,0.385885,0.947917,0.530929,0.555138
23,USAD,72,completed,0.200500,0.441776,0.906250,0.386882,0.556480
24,PCA_SPE,82,completed,0.220598,0.414070,0.857639,0.293272,0.579122
25,IsolationForest,82,completed,0.213364,0.292212,0.555556,0.071791,0.570490
26,DenseAE,82,completed,0.234984,0.437546,0.836806,0.259534,0.573866
27,LSTMAE,82,completed,0.222325,0.428334,0.767361,0.269126,0.564117
28,ConvAE,82,completed,0.194169,0.433564,0.927083,0.467769,0.556287
29,USAD,82,completed,0.215230,0.434161,0.854167,0.315047,0.556429

## Audit the new baseline records

In [6]:
result_dir = manuscript_result_root(config) / "baselines"
for file_name in [
    "runs.csv",
    "fault_summary.csv",
    "threshold_sensitivity.csv",
    "gas_natural_metrics.csv",
    "skab_native_metrics.csv",
]:
    path = result_dir / file_name
    if path.exists():
        print(f"\n{file_name}: {path}")
        display(pd.read_csv(path).tail(20))

runs.csv: /home/commu10/Documents/BT/cross_domain_drift_detection_manuscript_v2/cross_domain_drift_detection/results/manuscript_v2/baselines/runs.csv

,timestamp_utc,experiment_key,run_id,dataset,model,variant,seed,family,evaluation_set,experiment_version,...,validation_score_median,validation_score_p99,native_precision,native_recall,native_f1,native_auroc,native_auprc,native_event_recall,native_false_positive_rate,native_sequence_count
40,2026-07-29T01:00:11.506232+00:00,5141ffffa7f0d10a81fb,skab_ConvAE_52_5141ffff,skab,ConvAE,published_baseline,52,baselines,scenario_grid,manuscript_v2,...,0.005680,0.009937,0.388369,0.999728,0.557852,0.775280,0.696842,1.0,0.988132,34.0
41,2026-07-29T01:00:50.293164+00:00,c23d3b56fecca0fbb6e7,skab_USAD_52_c23d3b56,skab,USAD,published_baseline,52,baselines,scenario_grid,manuscript_v2,...,0.148107,0.183023,0.386902,1.000000,0.556429,0.853674,0.818014,1.0,0.993808,34.0
42,2026-07-29T01:01:24.633672+00:00,727763b29aaee2120aa1,skab_PCA_SPE_62_727763b2,skab,PCA_SPE,published_baseline,62,baselines,scenario_grid,manuscript_v2,...,0.056548,0.081207,0.415476,0.996460,0.579672,0.754260,0.671513,1.0,0.927417,34.0
43,2026-07-29T01:02:13.946433+00:00,40ac25bedec94610dad5,skab_IsolationForest_62_40ac25be,skab,IsolationForest,published_baseline,62,baselines,scenario_grid,manuscript_v2,...,0.506490,0.540003,0.406976,0.979590,0.568372,0.562946,0.484639,1.0,0.935157,34.0
44,2026-07-29T01:02:52.327265+00:00,220411476d694ceaf350,skab_DenseAE_62_22041147,skab,DenseAE,published_baseline,62,baselines,scenario_grid,manuscript_v2,...,0.062723,0.093518,0.413198,0.977669,0.571505,0.719592,0.629101,1.0,0.918129,34.0
45,2026-07-29T01:03:30.204381+00:00,aecf7c6c44d90a59a015,skab_LSTMAE_62_aecf7c6c,skab,LSTMAE,published_baseline,62,baselines,scenario_grid,manuscript_v2,...,0.087778,0.120075,0.387678,1.000000,0.557207,0.865453,0.842154,1.0,0.990884,34.0
46,2026-07-29T01:04:09.423086+00:00,080bb68c1595d9bbd50a,skab_ConvAE_62_080bb68c,skab,ConvAE,published_baseline,62,baselines,scenario_grid,manuscript_v2,...,0.005982,0.011068,0.388347,0.999455,0.557761,0.806581,0.738086,1.0,0.988304,34.0
47,2026-07-29T01:04:49.122636+00:00,c40c5d231d42a5bf0edd,skab_USAD_62_c40c5d23,skab,USAD,published_baseline,62,baselines,scenario_grid,manuscript_v2,...,0.141224,0.172372,0.386902,1.000000,0.556429,0.854328,0.819582,1.0,0.993808,34.0
48,2026-07-29T01:05:25.161759+00:00,40d80d43aec8ef1bfd5e,skab_PCA_SPE_72_40d80d43,skab,PCA_SPE,published_baseline,72,baselines,scenario_grid,manuscript_v2,...,0.056162,0.080477,0.415191,0.997004,0.579573,0.759512,0.675814,1.0,0.928449,34.0
49,2026-07-29T01:06:17.178752+00:00,7a51248736256cbeeec1,skab_IsolationForest_72_7a512487,skab,IsolationForest,published_baseline,72,baselines,scenario_grid,manuscript_v2,...,0.505632,0.535322,0.396738,0.990473,0.563367,0.568004,0.495752,1.0,0.959924,34.0
50,2026-07-29T01:06:57.218290+00:00,84f941aaf32f7741cec3,skab_DenseAE_72_84f941aa,skab,DenseAE,published_baseline,72,baselines,scenario_grid,manuscript_v2,...,0.064562,0.092390,0.409898,0.977669,0.569462,0.606005,0.569368,1.0,0.923633,34.0
51,2026-07-29T01:07:37.833550+00:00,50e768453aa6ea6b5b11,skab_LSTMAE_72_50e76845,skab,LSTMAE,published_baseline,72,baselines,scenario_grid,manuscript_v2,...,0.088305,0.126856,0.394781,1.000000,0.563536,0.860554,0.839051,1.0,0.972308,34.0
52,2026-07-29T01:08:17.606403+00:00,411ba74fb3da469db759,skab_ConvAE_72_411ba74f,skab,ConvAE,published_baseline,72,baselines,scenario_grid,manuscript_v2,...,0.007735,0.013099,0.385587,1.000000,0.555138,0.558315,0.526288,1.0,0.998452,34.0
53,2026-07-29T01:08:57.962002+00:00,348aad56b8ee20ad8c13,skab_USAD_72_348aad56,skab,USAD,published_baseline,72,baselines,scenario_grid,manuscript_v2,...,0.139734,0.172148,0.386956,1.000000,0.556480,0.864457,0.837331,1.0,0.993636,34.0
54,2026-07-29T01:09:33.996083+00:00,d6e26195444209a68f13,skab_PCA_SPE_82_d6e26195,skab,PCA_SPE,published_baseline,82,baselines,scenario_grid,manuscript_v2,...,0.056074,0.080905,0.414559,0.996732,0.579122,0.755447,0.672100,1.0,0.928793,34.0
55,2026-07-29T01:10:25.854384+00:00,c9f75853b5f0a8e3ccaa,skab_IsolationForest_82_c9f75853,skab,IsolationForest,published_baseline,82,baselines,scenario_grid,manuscript_v2,...,0.515116,0.546714,0.409432,0.981496,0.570490,0.554059,0.484715,1.0,0.934125,34.0
56,2026-07-29T01:11:06.199595+00:00,b32864d89644df53673d,skab_DenseAE_82_b32864d8,skab,DenseAE,published_baseline,82,baselines,scenario_grid,manuscript_v2,...,0.061533,0.089135,0.414870,0.980664,0.573866,0.653716,0.589652,1.0,0.918817,34.0
57,2026-07-29T01:11:48.400135+00:00,de424348a55e912dfdfa,skab_LSTMAE_82_de424348,skab,LSTMAE,published_baseline,82,baselines,scenario_grid,manuscript_v2,...,0.088184,0.124227,0.395764,0.999183,0.564117,0.861562,0.838176,1.0,0.970244,34.0
58,2026-07-29T01:12:29.016953+00:00,b9f8db6ef6281b85a7ac,skab_ConvAE_82_b9f8db6e,skab,ConvAE,published_baseline,82,baselines,scenario_grid,manuscript_v2,...,0.006913,0.012187,0.386702,1.000000,0.556287,0.734726,0.646569,1.0,0.993980,34.0
59,2026-07-29T01:13:09.003348+00:00,d0969e023e922d8368bb,skab_USAD_82_d0969e02,skab,USAD,published_baseline,82,baselines,scenario_grid,manuscript_v2,...,0.149090,0.182819,0.386902,1.000000,0.556429,0.861380,0.835981,1.0,0.993808,34.0

fault_summary.csv: /home/commu10/Documents/BT/cross_domain_drift_detection_manuscript_v2/cross_domain_drift_detection/results/manuscript_v2/baselines/fault_summary.csv

,fault_type,precision,recall,f1,auroc,auprc,event_recall,mean_detection_delay_windows,false_positive_rate,experiment_key,run_id,dataset,model,variant,seed,family,experiment_version,config_fingerprint,scenario_profile
340,proportional,0.037287,0.141516,0.056471,0.453357,0.074552,0.666667,14.468750,0.262808,b32864d89644df53673d,skab_DenseAE_82_b32864d8,skab,DenseAE,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
341,stuck,0.031596,0.086094,0.044249,0.339253,0.069479,0.416667,19.550000,0.262436,b32864d89644df53673d,skab_DenseAE_82_b32864d8,skab,DenseAE,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
342,additive,0.201826,0.836390,0.315369,0.893209,0.628511,0.979167,2.425532,0.270533,de424348a55e912dfdfa,skab_LSTMAE_82_de424348,skab,LSTMAE,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
343,common_mode,0.226659,0.942154,0.354526,0.948628,0.757857,1.000000,0.583333,0.268199,de424348a55e912dfdfa,skab_LSTMAE_82_de424348,skab,LSTMAE,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
344,gradual,0.162256,0.652208,0.249849,0.775665,0.394034,0.979167,10.255319,0.267325,de424348a55e912dfdfa,skab_LSTMAE_82_de424348,skab,LSTMAE,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
345,noise,0.214493,0.855855,0.332821,0.905009,0.640374,1.000000,2.041667,0.264493,de424348a55e912dfdfa,skab_LSTMAE_82_de424348,skab,LSTMAE,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
346,proportional,0.025975,0.107794,0.040106,0.409138,0.073153,0.416667,13.950000,0.272440,de424348a55e912dfdfa,skab_LSTMAE_82_de424348,skab,LSTMAE,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
347,stuck,0.029761,0.077217,0.041279,0.362971,0.076073,0.229167,15.727273,0.271767,de424348a55e912dfdfa,skab_LSTMAE_82_de424348,skab,LSTMAE,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
348,additive,0.145469,0.922780,0.243820,0.866052,0.612952,1.000000,0.729167,0.466757,b9f8db6ef6281b85a7ac,skab_ConvAE_82_b9f8db6e,skab,ConvAE,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
349,common_mode,0.148758,0.943692,0.248563,0.911515,0.720068,1.000000,0.312500,0.465572,b9f8db6ef6281b85a7ac,skab_ConvAE_82_b9f8db6e,skab,ConvAE,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
350,gradual,0.125592,0.792524,0.209611,0.737845,0.393257,0.979167,5.425532,0.464973,b9f8db6ef6281b85a7ac,skab_ConvAE_82_b9f8db6e,skab,ConvAE,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
351,noise,0.145044,0.937323,0.243718,0.899797,0.720231,1.000000,0.979167,0.469152,b9f8db6ef6281b85a7ac,skab_ConvAE_82_b9f8db6e,skab,ConvAE,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
352,proportional,0.065479,0.408169,0.108146,0.438764,0.076626,0.875000,7.809524,0.469743,b9f8db6ef6281b85a7ac,skab_ConvAE_82_b9f8db6e,skab,ConvAE,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
353,stuck,0.069498,0.328340,0.111156,0.394791,0.078249,0.708333,7.205882,0.470415,b9f8db6ef6281b85a7ac,skab_ConvAE_82_b9f8db6e,skab,ConvAE,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
354,additive,0.185838,0.867595,0.296593,0.886288,0.632914,0.979167,2.212766,0.315913,d0969e023e922d8368bb,skab_USAD_82_d0969e02,skab,USAD,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
355,common_mode,0.201552,0.941485,0.321935,0.942303,0.759804,1.000000,0.500000,0.314289,d0969e023e922d8368bb,skab_USAD_82_d0969e02,skab,USAD,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
356,gradual,0.157750,0.719299,0.249725,0.774667,0.411430,1.000000,7.729167,0.314234,d0969e023e922d8368bb,skab_USAD_82_d0969e02,skab,USAD,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
357,noise,0.197547,0.895543,0.314061,0.909055,0.649876,1.000000,1.541667,0.310427,d0969e023e922d8368bb,skab_USAD_82_d0969e02,skab,USAD,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
358,proportional,0.031053,0.161463,0.049715,0.402201,0.070975,0.625000,10.166667,0.318009,d0969e023e922d8368bb,skab_USAD_82_d0969e02,skab,USAD,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
359,stuck,0.039753,0.138274,0.059354,0.372756,0.079967,0.520833,14.720000,0.317413,d0969e023e922d8368bb,skab_USAD_82_d0969e02,skab,USAD,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript

threshold_sensitivity.csv: /home/commu10/Documents/BT/cross_domain_drift_detection_manuscript_v2/cross_domain_drift_detection/results/manuscript_v2/baselines/threshold_sensitivity.csv

,threshold_name,threshold,precision,recall,f1,auroc,auprc,event_recall,mean_detection_delay_windows,false_positive_rate,...,experiment_key,run_id,dataset,model,variant,seed,family,experiment_version,config_fingerprint,scenario_profile
400,quantile_0.975,0.121494,0.141485,0.587995,0.220472,0.715770,0.428334,0.788194,5.431718,0.279882,...,de424348a55e912dfdfa,skab_LSTMAE_82_de424348,skab,LSTMAE,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
401,quantile_0.99,0.124227,0.143495,0.578603,0.222325,0.715770,0.428334,0.767361,5.312217,0.269126,...,de424348a55e912dfdfa,skab_LSTMAE_82_de424348,skab,LSTMAE,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
402,quantile_0.995,0.125531,0.143480,0.575008,0.221997,0.715770,0.428334,0.763889,5.200000,0.266898,...,de424348a55e912dfdfa,skab_LSTMAE_82_de424348,skab,LSTMAE,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
403,mad_4,0.161846,0.190084,0.485975,0.265086,0.715770,0.428334,0.638889,6.961957,0.138727,...,de424348a55e912dfdfa,skab_LSTMAE_82_de424348,skab,LSTMAE,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
404,mad_6,0.198677,0.236525,0.419799,0.295672,0.715770,0.428334,0.552083,5.874214,0.073094,...,de424348a55e912dfdfa,skab_LSTMAE_82_de424348,skab,LSTMAE,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
405,mad_8,0.235508,0.304240,0.378162,0.330941,0.715770,0.428334,0.493056,5.295775,0.030652,...,de424348a55e912dfdfa,skab_LSTMAE_82_de424348,skab,LSTMAE,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
406,quantile_0.95,0.010512,0.099267,0.824183,0.172037,0.708127,0.433564,0.972222,1.757143,0.655753,...,b9f8db6ef6281b85a7ac,skab_ConvAE_82_b9f8db6e,skab,ConvAE,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
407,quantile_0.975,0.011163,0.103575,0.784224,0.177412,0.708127,0.433564,0.965278,2.377698,0.591378,...,b9f8db6ef6281b85a7ac,skab_ConvAE_82_b9f8db6e,skab,ConvAE,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
408,quantile_0.99,0.012187,0.116640,0.722138,0.194169,0.708127,0.433564,0.927083,3.464419,0.467769,...,b9f8db6ef6281b85a7ac,skab_ConvAE_82_b9f8db6e,skab,ConvAE,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
409,quantile_0.995,0.012744,0.124111,0.689914,0.203119,0.708127,0.433564,0.899306,3.849421,0.411151,...,b9f8db6ef6281b85a7ac,skab_ConvAE_82_b9f8db6e,skab,ConvAE,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
410,mad_4,0.014814,0.148108,0.592728,0.228737,0.708127,0.433564,0.826389,6.655462,0.268525,...,b9f8db6ef6281b85a7ac,skab_ConvAE_82_b9f8db6e,skab,ConvAE,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
411,mad_6,0.018764,0.139481,0.510798,0.211648,0.708127,0.433564,0.673611,6.716495,0.236345,...,b9f8db6ef6281b85a7ac,skab_ConvAE_82_b9f8db6e,skab,ConvAE,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
412,mad_8,0.022715,0.144575,0.470320,0.213833,0.708127,0.433564,0.631944,6.934066,0.198086,...,b9f8db6ef6281b85a7ac,skab_ConvAE_82_b9f8db6e,skab,ConvAE,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
413,quantile_0.95,0.177050,0.128437,0.651555,0.207530,0.714545,0.434161,0.892361,4.848249,0.361060,...,d0969e023e922d8368bb,skab_USAD_82_d0969e02,skab,USAD,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
414,quantile_0.975,0.180578,0.132180,0.632589,0.211470,0.714545,0.434161,0.871528,4.701195,0.333821,...,d0969e023e922d8368bb,skab_USAD_82_d0969e02,skab,USAD,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
415,quantile_0.99,0.182819,0.135582,0.620610,0.215230,0.714545,0.434161,0.854167,5.065041,0.315047,...,d0969e023e922d8368bb,skab_USAD_82_d0969e02,skab,USAD,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
416,quantile_0.995,0.185680,0.141412,0.605572,0.221744,0.714545,0.434161,0.840278,5.334711,0.289713,...,d0969e023e922d8368bb,skab_USAD_82_d0969e02,skab,USAD,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
417,mad_4,0.238776,0.209669,0.475483,0.282958,0.714545,0.434161,0.611111,6.062500,0.113492,...,d0969e023e922d8368bb,skab_USAD_82_d0969e02,skab,USAD,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
418,mad_6,0.283619,0.271914,0.407832,0.319150,0.714545,0.434161,0.545139,5.853503,0.051873,...,d0969e023e922d8368bb,skab_USAD_82_d0969e02,skab,USAD,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
419,mad_8,0.328462,0.319420,0.367988,0.336655,0.714545,0.434161,0.472222,5.338235,0.023579,...,d0969e023e922d8368bb,skab_USAD_82_d0969e02,skab,USAD,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript

gas_natural_metrics.csv: /home/commu10/Documents/BT/cross_domain_drift_detection_manuscript_v2/cross_domain_drift_detection/results/manuscript_v2/baselines/gas_natural_metrics.csv

,batch,window_count,median_score,mean_score,p95_score,threshold_exceedance_rate,robust_shift_from_validation,threshold,experiment_key,run_id,dataset,model,variant,seed,family,experiment_version,config_fingerprint,scenario_profile
160,9,117,0.634707,8.350569,106.518677,0.076923,-0.913322,3.410444,cd5cdca9d127b9bddc2a,gas_sensor_DenseAE_82_cd5cdca9,gas_sensor,DenseAE,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
161,10,900,1.728287,3.147717,8.987833,0.355556,0.188825,3.410444,cd5cdca9d127b9bddc2a,gas_sensor_DenseAE_82_cd5cdca9,gas_sensor,DenseAE,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
162,5,42,0.692058,1.127868,3.231358,0.000000,-0.278412,3.720871,016b943bc1e7b33f51f4,gas_sensor_LSTMAE_82_016b943b,gas_sensor,LSTMAE,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
163,6,575,0.611325,0.692271,1.535047,0.000000,-0.339967,3.720871,016b943bc1e7b33f51f4,gas_sensor_LSTMAE_82_016b943b,gas_sensor,LSTMAE,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
164,7,903,0.994269,1.046285,1.653345,0.000000,-0.047992,3.720871,016b943bc1e7b33f51f4,gas_sensor_LSTMAE_82_016b943b,gas_sensor,LSTMAE,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
165,8,74,1.174213,1.351027,3.950581,0.067568,0.089207,3.720871,016b943bc1e7b33f51f4,gas_sensor_LSTMAE_82_016b943b,gas_sensor,LSTMAE,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
166,9,117,0.454231,7.901778,105.365372,0.068376,-0.459743,3.720871,016b943bc1e7b33f51f4,gas_sensor_LSTMAE_82_016b943b,gas_sensor,LSTMAE,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
167,10,900,1.381478,2.610685,7.578437,0.278889,0.247236,3.720871,016b943bc1e7b33f51f4,gas_sensor_LSTMAE_82_016b943b,gas_sensor,LSTMAE,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
168,5,42,0.485815,0.784521,2.506505,0.142857,-0.532064,1.432067,59812d7fea15f274f544,gas_sensor_ConvAE_82_59812d7f,gas_sensor,ConvAE,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
169,6,575,0.424730,0.487278,1.040633,0.003478,-0.711571,1.432067,59812d7fea15f274f544,gas_sensor_ConvAE_82_59812d7f,gas_sensor,ConvAE,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
170,7,903,0.759109,0.803433,1.256389,0.003322,0.271049,1.432067,59812d7fea15f274f544,gas_sensor_ConvAE_82_59812d7f,gas_sensor,ConvAE,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
171,8,74,0.624390,0.943589,3.550406,0.108108,-0.124841,1.432067,59812d7fea15f274f544,gas_sensor_ConvAE_82_59812d7f,gas_sensor,ConvAE,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
172,9,117,0.248840,7.581874,107.209869,0.068376,-1.228449,1.432067,59812d7fea15f274f544,gas_sensor_ConvAE_82_59812d7f,gas_sensor,ConvAE,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
173,10,900,0.800184,2.283682,7.347219,0.425556,0.391751,1.432067,59812d7fea15f274f544,gas_sensor_ConvAE_82_59812d7f,gas_sensor,ConvAE,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
174,5,42,0.966841,1.501499,3.676565,0.000000,-0.546780,4.575801,0a4f360bbacfe6cf7056,gas_sensor_USAD_82_0a4f360b,gas_sensor,USAD,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
175,6,575,0.826330,0.921385,1.910375,0.000000,-0.636266,4.575801,0a4f360bbacfe6cf7056,gas_sensor_USAD_82_0a4f360b,gas_sensor,USAD,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
176,7,903,1.128129,1.224692,1.936007,0.000000,-0.444062,4.575801,0a4f360bbacfe6cf7056,gas_sensor_USAD_82_0a4f360b,gas_sensor,USAD,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
177,8,74,1.377967,1.596600,4.195660,0.027027,-0.284950,4.575801,0a4f360bbacfe6cf7056,gas_sensor_USAD_82_0a4f360b,gas_sensor,USAD,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
178,9,117,0.806687,8.139289,105.671593,0.068376,-0.648776,4.575801,0a4f360bbacfe6cf7056,gas_sensor_USAD_82_0a4f360b,gas_sensor,USAD,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
179,10,900,1.350045,2.642486,7.660940,0.185556,-0.302732,4.575801,0a4f360bbacfe6cf7056,gas_sensor_USAD_82_0a4f360b,gas_sensor,USAD,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript

skab_native_metrics.csv: /home/commu10/Documents/BT/cross_domain_drift_detection_manuscript_v2/cross_domain_drift_detection/results/manuscript_v2/baselines/skab_native_metrics.csv

,sequence_id,source_file,point_count,anomaly_points,changepoints,threshold,precision,recall,f1,auroc,...,experiment_key,run_id,dataset,model,variant,seed,family,experiment_version,config_fingerprint,scenario_profile
1000,14,/home/commu10/Documents/BT/cross_domain_drift_...,1147,401,4,0.182819,0.387097,1.0,0.558140,0.934914,...,d0969e023e922d8368bb,skab_USAD_82_d0969e02,skab,USAD,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
1001,15,/home/commu10/Documents/BT/cross_domain_drift_...,1145,402,4,0.182819,0.387097,1.0,0.558140,0.772959,...,d0969e023e922d8368bb,skab_USAD_82_d0969e02,skab,USAD,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
1002,16,/home/commu10/Documents/BT/cross_domain_drift_...,1146,401,4,0.182819,0.387097,1.0,0.558140,0.990037,...,d0969e023e922d8368bb,skab_USAD_82_d0969e02,skab,USAD,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
1003,17,/home/commu10/Documents/BT/cross_domain_drift_...,1141,399,4,0.182819,0.384892,1.0,0.555844,0.865661,...,d0969e023e922d8368bb,skab_USAD_82_d0969e02,skab,USAD,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
1004,18,/home/commu10/Documents/BT/cross_domain_drift_...,1140,399,4,0.182819,0.388489,1.0,0.559585,0.963126,...,d0969e023e922d8368bb,skab_USAD_82_d0969e02,skab,USAD,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
1005,19,/home/commu10/Documents/BT/cross_domain_drift_...,1140,399,4,0.182819,0.388489,1.0,0.559585,0.782081,...,d0969e023e922d8368bb,skab_USAD_82_d0969e02,skab,USAD,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
1006,20,/home/commu10/Documents/BT/cross_domain_drift_...,1139,399,4,0.182819,0.386282,1.0,0.557292,0.909456,...,d0969e023e922d8368bb,skab_USAD_82_d0969e02,skab,USAD,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
1007,21,/home/commu10/Documents/BT/cross_domain_drift_...,1150,404,4,0.182819,0.389286,1.0,0.560411,0.988036,...,d0969e023e922d8368bb,skab_USAD_82_d0969e02,skab,USAD,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
1008,22,/home/commu10/Documents/BT/cross_domain_drift_...,1075,337,3,0.182819,0.352490,1.0,0.521246,0.770196,...,d0969e023e922d8368bb,skab_USAD_82_d0969e02,skab,USAD,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
1009,23,/home/commu10/Documents/BT/cross_domain_drift_...,1148,404,4,0.182819,0.389286,1.0,0.560411,0.804872,...,d0969e023e922d8368bb,skab_USAD_82_d0969e02,skab,USAD,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
1010,24,/home/commu10/Documents/BT/cross_domain_drift_...,1095,349,4,0.182819,0.357143,1.0,0.526316,0.716713,...,d0969e023e922d8368bb,skab_USAD_82_d0969e02,skab,USAD,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
1011,25,/home/commu10/Documents/BT/cross_domain_drift_...,1154,403,4,0.182819,0.384342,1.0,0.555270,0.816206,...,d0969e023e922d8368bb,skab_USAD_82_d0969e02,skab,USAD,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
1012,26,/home/commu10/Documents/BT/cross_domain_drift_...,1154,405,4,0.182819,0.387900,1.0,0.558974,0.878280,...,d0969e023e922d8368bb,skab_USAD_82_d0969e02,skab,USAD,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
1013,27,/home/commu10/Documents/BT/cross_domain_drift_...,1094,405,4,0.182819,0.409774,1.0,0.581333,0.926606,...,d0969e023e922d8368bb,skab_USAD_82_d0969e02,skab,USAD,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
1014,28,/home/commu10/Documents/BT/cross_domain_drift_...,1144,400,4,0.182819,0.383513,1.0,0.554404,0.982612,...,d0969e023e922d8368bb,skab_USAD_82_d0969e02,skab,USAD,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
1015,29,/home/commu10/Documents/BT/cross_domain_drift_...,1148,402,4,0.182819,0.385714,1.0,0.556701,0.780631,...,d0969e023e922d8368bb,skab_USAD_82_d0969e02,skab,USAD,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
1016,30,/home/commu10/Documents/BT/cross_domain_drift_...,1125,394,4,0.182819,0.386861,1.0,0.557895,0.601808,...,d0969e023e922d8368bb,skab_USAD_82_d0969e02,skab,USAD,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
1017,31,/home/commu10/Documents/BT/cross_domain_drift_...,1063,333,4,0.182819,0.352713,1.0,0.521490,0.935185,...,d0969e023e922d8368bb,skab_USAD_82_d0969e02,skab,USAD,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
1018,32,/home/commu10/Documents/BT/cross_domain_drift_...,1129,395,4,0.182819,0.385455,1.0,0.556430,0.869376,...,d0969e023e922d8368bb,skab_USAD_82_d0969e02,skab,USAD,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript
1019,33,/home/commu10/Documents/BT/cross_domain_drift_...,995,395,4,0.182819,0.439834,1.0,0.610951,0.715304,...,d0969e023e922d8368bb,skab_USAD_82_d0969e02,skab,USAD,published_baseline,82,baselines,manuscript_v2,a520efd426e55d648ca4,manuscript

## Distinct-seed check

In [7]:
runs = pd.read_csv(result_dir / "runs.csv")
completed = runs[runs["status"] == "completed"]
seed_audit = completed.groupby(["dataset", "model"], as_index=False)["seed"].nunique().rename(columns={"seed": "distinct_seed_count"})
display(seed_audit)
expected = len(SEEDS)
if (seed_audit["distinct_seed_count"] < expected).any():
    print("Some models are incomplete. Inspect failed rows before aggregation.")
else:
    print("All completed baseline groups contain the requested independent seeds.")

       dataset            model  distinct_seed_count
0   gas_sensor           ConvAE                    5
1   gas_sensor          DenseAE                    5
2   gas_sensor  IsolationForest                    5
3   gas_sensor           LSTMAE                    5
4   gas_sensor          PCA_SPE                    5
5   gas_sensor             USAD                    5
6         skab           ConvAE                    5
7         skab          DenseAE                    5
8         skab  IsolationForest                    5
9         skab           LSTMAE                    5
10        skab          PCA_SPE                    5
11        skab             USAD                    5

All completed baseline groups contain the requested independent seeds.